### PR TITLE
Parse SDK submodule => Carthage dependency

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by flovilmart** [comment]
Can you remove the Carthage folder and add it in the .gitignore?

**Comment by AndrewSB** [comment]
yup!

**Comment by AndrewSB** [comment]
bump

I'd like to delete my fork

**Comment by flovilmart** [comment]
I don’t maintain this project anymore either. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
